name: build

permissions:
  contents: write

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  PROJECT: lua-language-server
  BIN_DIR: bin

jobs:
  compile:
    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: ubuntu-20.04,   target: linux,   platform: linux-x64    }
          - { os: ubuntu-20.04,   target: linux,   platform: linux-arm64  }
          - { os: macos-11,       target: darwin,  platform: darwin-x64   }
          - { os: macos-11,       target: darwin,  platform: darwin-arm64 }
          - { os: windows-latest, target: windows, platform: win32-ia32   }
          - { os: windows-latest, target: windows, platform: win32-x64    }
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Luamake
        uses: actboy168/setup-luamake@master

      - name: Luamake
        run: luamake -platform ${{ matrix.platform }}

      - name: Setting up workflow variables
        id: vars
        shell: bash
        run: |
          # Package version
          PKG_VERSION=${GITHUB_SHA:0:7}

          # Package suffix relative to the platform
          if [[ "${{ matrix.target }}" = windows ]]; then
            PKG_SUFFIX="zip"
          else
            PKG_SUFFIX="tar.gz"
          fi

          # Package name w/ version
          PKG_BASENAME="${{ env.PROJECT }}-${PKG_VERSION}-${{ matrix.platform }}"

          echo PKG_BASENAME=${PKG_BASENAME}           >> $GITHUB_OUTPUT

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.vars.outputs.PKG_BASENAME }}
          path: |
            ${{ env.BIN_DIR }}
            main.lua
            debugger.lua
            LICENSE
            changelog.md
            locale
            doc
            meta
            script
